#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

command = nil
name = nil
command = ARGV[0].downcase unless ARGV[0].nil?
name    = ARGV[1]
date    = ARGV[2]


params = { command: command, visit: { school_name: name, visit_date: date}}
controller = CollegeTraxController.new(params)
routes = {"add" => :create_visit, "list" => :index_all, "remove" => :destroy,
           "rank" => :get_rankings, "rankings" => :index_rankings, "view" => :index_school}

if command.nil?
  Menu.print_menu
elsif route = routes[command]
  controller.send route
else
    puts "CollegeTrax does not (yet?) support the '#{command}' command.\n\n"
  puts <<EOS
Currently supported commands are:
* ./trax
* ./trax add
* ./trax rank "School Name in quotes"
* ./trax list
* ./trax rankings
* ./trax remove "School Name in quotes"

See the README for more details
EOS
end